version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck   
    - govet      
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - err113
    - errname
    - funlen
    - funcorder
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gosec
    - iface
    - lll
    - interfacebloat
    - musttag
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - reassign
    - sqlclosecheck
    - tagalign
    - testifylint
    - testableexamples
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck